example <- matrix(c(1, 2, 3, 4, 5, 6, 7, 8), nrow = 4, ncol = 2)
install.packages("ggplot2")
library(ggplot2)
library()
remove.packages("ggplot2")
install.packages("ggplot2")
library("ggplot2")
version
sessionInfo()
help(package = "ggplot2")
browseVignettes("ggplot2")
help(package = "devtools")
install.packages("devtools")
help(package = "devtools")
help(package = "KernSmooth")
packageDescription("KernSmooth")
citation("KernSmooth")
